### ISSUE TITLE
Car running without input from arduino 

### ISSUE THREAD

**Issue by gamer2199** [hamuchiwa/AutoRCCar#92]
The script rc_control_test.py is running but i am not sure whether its taking my input or not. The remote buttons have 4 pins connected to the board of which i have soldered wires to two pins because connecting the wire to single pin doesn't make the car work. After connecting to the 2 pins the car goes only in forward direction. Urgently help required!! 
![img_20180403_165315887](https://user-images.githubusercontent.com/29453894/38246620-006dc1d6-3760-11e8-8411-c8123e5e0185.jpg)
![img_20180403_165336715_hdr](https://user-images.githubusercontent.com/29453894/38246621-00ba7c38-3760-11e8-8512-d04328ed248e.jpg)

**Comment by Gooose1909** [comment]
Let me guess you are from india??
I had to deal with the same type of cicuit to interface with arduino
I failed cos the other 2 pins runs on -ve voltage which ur arduino cant
supply
Thats what your problem is

**Comment by gamer2199** [comment]
Any solution for this?

**Comment by Gooose1909** [comment]
I made myself a new rc car using L298n motor driver with RF transmitter and
reciever
Works like a charm

**Comment by gamer2199** [comment]
i guess your transmitter is the remote and you have connected it to the arduino?

**Comment by Gooose1909** [comment]
Yeah
Arduino + transmitter
And reciever + arduino to control motor driver for car movement

**Comment by gamer2199** [comment]
wait you have 2 arduinos in the project?

**Comment by Gooose1909** [comment]
Yup

**Comment by gamer2199** [comment]
Can you post an image if possible? it would give me a clear understanding

**Comment by Gooose1909** [comment]
Give me a hour will post the pic soon

**Comment by gamer2199** [comment]
Thanks a lot..it will really help me :)

**Comment by gamer2199** [comment]
Hey....is the project ready? i am in a hurry to see it because my submission are approaching and i am stuck

**Comment by gamer2199** [comment]
sorry to bother you but can you help me with the code?

**Comment by Gooose1909** [comment]
Yeah

**Comment by gamer2199** [comment]
are there a lot of changes?

**Comment by Gooose1909** [comment]
Nope
His code remains the same
I just made my own RC car
Thats all

**Comment by gamer2199** [comment]
thats awesome. Did you follow any guide online on making the RC car?

**Comment by Gooose1909** [comment]
Nope
Basic arduino programming is fine

**Comment by gamer2199** [comment]
Can you post your arduino code or is it the same as the one provided with this project?

**Comment by Gooose1909** [comment]
Ok

**Comment by gamer2199** [comment]
Thanks in advance!

**Comment by tkajbaje** [comment]
I have same type of remote for my rc car what I did was I used a 4066 IC for controlling it using arduino it is a quad bilateral switch IC.You have to connect the buttons using wires to every input and output of the IC 

![4066-quad-bilateral-switch-pinout](https://user-images.githubusercontent.com/9403387/38316247-e7e2c7fe-3847-11e8-8a1d-473a341b87e0.png)

for eg connect two wires of forward button with input1 and output1 of ic and connect Control A to arduino that pin will control the forward switch of the car.you just have to change the arduino sketch a little bit to make the desired pin HIGH for a duration of time.the IC consists of four switches which are in open condition initially when the control pin of the corresponding switch is provided with 5v supply it goes into closed state.This seemed to be a simple solution to me.

**Comment by gamer2199** [comment]
have you tried this solution? for now my group is deciding on doing what goose said but i am still gonna give this a try

**Comment by tkajbaje** [comment]
yes I have tried this solution,I can control my car through pc using this method.

**Comment by gamer2199** [comment]
do you have a picture of the connections right now?

**Comment by tkajbaje** [comment]
![img_20180405_192736](https://user-images.githubusercontent.com/9403387/38370686-51c0c476-3908-11e8-9246-bbfda1735832.jpg)
![img_20180405_192741](https://user-images.githubusercontent.com/9403387/38370687-520f7d3c-3908-11e8-8363-4e0d99b73cac.jpg)
![img_20180405_192818](https://user-images.githubusercontent.com/9403387/38370688-52425a72-3908-11e8-8a9f-c40fd7301a74.jpg)
![img_20180405_192821](https://user-images.githubusercontent.com/9403387/38370689-526ecce2-3908-11e8-97a5-2eeb43959601.jpg)
![img_20180405_193500](https://user-images.githubusercontent.com/9403387/38371058-2bad5c30-3909-11e8-8fa5-d6f7294a0fb7.jpg)
![img_20180405_193511](https://user-images.githubusercontent.com/9403387/38371060-2be506c6-3909-11e8-9814-fb2662512196.jpg)

**Comment by gamer2199** [comment]
Thanks a lot..one last question...the power to the remote control board is through the battery right?

**Comment by tkajbaje** [comment]
Yes.You have to connect only the control and power pins of the IC to Arduino.The remote is powered by separate cells.

**Comment by gamer2199** [comment]
You are a life saver!!! and Can you please post your arduino code? Sorry for asking so much but it will help me a lot

**Comment by tkajbaje** [comment]
[archive.zip](https://github.com/hamuchiwa/AutoRCCar/files/1880507/archive.zip)

**Comment by gamer2199** [comment]
Thanks a ton!! I hope this works in my project

**Comment by gamer2199** [comment]
i tried your solution but its still not working....did you supply negative voltage?

**Comment by tkajbaje** [comment]
I did not understand what you mean by supplying negative voltage,negative voltage to the remote control ? Yes,other than soldering two wires to each terminal of the switch I did not change anything in there and you have to power the RC by putting batteries in battery compartment and then connect the wires soldered to switch to IC.The IC needs 5v supply and GND connection.

**Comment by gamer2199** [comment]
i am not able to control the car using keypress..i have connected the ic as you said but no avail

**Comment by tkajbaje** [comment]
Can you post images of connections ??

**Comment by gamer2199** [comment]
![img_20180407_141304364](https://user-images.githubusercontent.com/29453894/38453119-101cb13a-3a6e-11e8-8212-520027ec4346.jpg)
![img_20180407_141321236_ll](https://user-images.githubusercontent.com/29453894/38453120-1046a940-3a6e-11e8-98f7-9ac0494408bd.jpg)
![img_20180407_141332666](https://user-images.githubusercontent.com/29453894/38453121-107dd6cc-3a6e-11e8-9663-b10c5fbf84b9.jpg)

**Comment by gamer2199** [comment]
no the pygame window doesnt popup

**Comment by tkajbaje** [comment]
go to the link I posted above.those files are modified for working with OpenCV 3.0 as guided by @hamuchiwa  in another thread.rc_driver.py is also modified.As you have moved on to testing the car with rc_driver.py I assume that the car now can be controlled using your pc.

**Comment by gamer2199** [comment]
yup i can control the car using my pc. I will run the rc_driver.py from your link later and let you know if any errors occur.

**Comment by gamer2199** [comment]
self.model = cv2.ml.ANN_MLP_load(file_path)
AttributeError: 'module' object has no attribute 'ANN_MLP_load'

this is the new error thats occuring...my open cv version is 3.1.0

**Comment by tkajbaje** [comment]
install OpenCV 3.4.1 for this to work.I followed [this](http://cyaninfinite.com/tutorials/installing-opencv-in-ubuntu-for-python-3/) tutorial.make sure you uninstall all previous versions before installing this one.

**Comment by gamer2199** [comment]
I installed open cv 3.4.1 and now its working but the car keeps turning left.Test accuracy was around 72%. Does it have to be higher and what was your accuracy when you ran the script?

**Comment by tkajbaje** [comment]
My accuracy was around 80% but I had another issue while I ran the script.The rate at which the frames were streamed from rpi to computer and the speed of the car were not matching so my car also used to keep turning left.I managed to tackle the issue by adding "self.stop()" after every move of the car so as to synchronize.but now the car runs slow(actually very slow).but it runs on track.

**Comment by gamer2199** [comment]
have you tried increasing the frame rate?

**Comment by tkajbaje** [comment]
Yes,I tried increasing the frame rate it streamed smoothly only in the test(stream_server_test.py) but in rc_driver.py it is still slow.I think the time taken by ml model to predict the output adds to the lag.

**Comment by gamer2199** [comment]
i want to increase the speed a bit...its too slow right now. What we I somehow control the speed of motor and increase the frames?

**Comment by tkajbaje** [comment]
If you increase the value of variable 'time' in Arduino sketch speed of the car will increase.framerate can be increased in stream client code for rpi.

**Comment by gamer2199** [comment]
where do we make the changes in stream client...i am having trouble finding it

**Comment by tkajbaje** [comment]
in raspberry pi folder in file stream_client.py change 'camera.framerate' to your desired framerate value.

**Comment by gamer2199** [comment]
i changed the frame rate at first but its doesn't do any effect while streaming

**Comment by kxrf97** [comment]
@gamer2199 tkajbaje solution could solve this issue?

**Comment by gamer2199** [comment]
@kxrf97 can you specify which issue exactly? If you are talking about the title, yes it did!

**Comment by kxrf97** [comment]
i have a controller almost same as yours

**Comment by kxrf97** [comment]
there are 4 pins for each push button

**Comment by kxrf97** [comment]
i connect one pin for one button, after i plug into my arduino, only forward and left are functioning. Reverse and right are not receiving any signal at all. May i know which 2 pins you soldier with your wire?

**Comment by kxrf97** [comment]
@gamer2199 
![test2](https://user-images.githubusercontent.com/47766697/53184637-5c880f80-3638-11e9-96d0-ea7f5ba36d11.jpg)
![test1](https://user-images.githubusercontent.com/47766697/53184638-5c880f80-3638-11e9-9660-54d0d467e7cf.jpg)

**Comment by gamer2199** [comment]
@kxrf97 sorry for the late reply. I did exactly the same thing that you have done here. Maybe its a connection/soldering issue or input issue? Is the PyGame window opening up?

**Comment by harshithdayananda** [comment]
@gamer2199 @tkajbaje need your help. my car was working before with optocouplers but now it stopped working and takes continuous input i.e without input keeps going forward. what do I do?
